SET FOREIGN_KEY_CHECKS=0;
LOAD DATA LOCAL INFILE 'sellerData.csv' INTO TABLE seller FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'locationData.csv' INTO TABLE location FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'bidderData.csv' INTO TABLE bidder FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'itemData.csv' INTO TABLE item FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'categoryData.csv' INTO TABLE category FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'bidData.csv' INTO TABLE bid FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
SET FOREIGN_KEY_CHECKS=1;


